#!/usr/bin/env R
#Title: general purpose data squashing ()
#Version: 0.1
#Date: 2017-03-07
#Author: Kishore R.Anekalla 
source("https://bioconductor.org/biocLite.R")
pkgs<-c("biomaRt","GenomicRanges","BiocParallel","heatmap3","genefilter","dplyr",
        "DESeq2","edgeR","Hmisc","ggplot2","readxl","Cairo","pheatmap",
        "gplots","calibrate","stringi","PoiClaClu")
for(i in 1:length(pkgs)){
  if(require(pkgs[i], character.only = TRUE)==FALSE){ install.packages(pkgs[i]);library(pkgs[i], character.only = TRUE)}
  else { library(pkgs[i],character.only = TRUE)}
}
# parallelization still needs to be implemented
#register(MulticoreParam(8))
# pca plot using rlog-transformed values
getpca_rlog<-function(x,y,cols,outputname){
  library(genefilter)
  library(ggplot2)
  if (file.exists(outputname)==F){
    dir.create(file.path(outputname))
  }
  normfile <- paste(outputname,"/",outputname,"_rlognorm.txt", sep="")
  scree_plot_file_name <- paste(outputname,"/",outputname,"_scree_plot.pdf", sep="")
  scree_plot_name <- paste("Scree plot for ", outputname, sep="")
  x<-data.frame(x[,6:length(colnames(x))]) # to make work for any htseq/granges output
  print(y) # Ensure that the columns and groups match if else
  #Condition<-paste(factor1,factor2,sep=":") # substitute for coldata but for now a file is preferred
  ddsMat <- DESeqDataSetFromMatrix(countData = x, colData = y, design =~condition) # condition can be generated by mixing the factors /coldata apparoach
  print("# of ensembl IDS in the unfiltered dataset")
  print(nrow(ddsMat))
  # filtering the set
  dds <- ddsMat[ rowSums(counts(ddsMat)) > 1, ] # filtering
  print("# of Ensembl Ids post filtering")
  print(nrow(dds))
  #
  rld <- rlog(dds, blind=TRUE)
  # distance matrix plot 
  library("PoiClaClu")
  library("pheatmap")
  library("RColorBrewer")
  poisd <- PoissonDistance(t(counts(dds)))
  samplePoisDistMatrix <- as.matrix( poisd$dd )
  rownames(samplePoisDistMatrix) <- paste( rld$samples)
  colnames(samplePoisDistMatrix) <- NULL
  head(samplePoisDistMatrix)
  dist_plot_file_name <- paste(outputname,"/",outputname,"_distance_plot.pdf", sep="")
  cairo_pdf(filename = dist_plot_file_name,bg = "white")
  pheatmap(samplePoisDistMatrix,clustering_distance_rows=poisd$dd,clustering_distance_cols=poisd$dd,
    col=tol21rainbow,main="distance matrix (poissons) plot")
  dev.off()
  #colorsinfo <- colorRampPalette( rev(brewer.pal(9, "Set3")) )(255)
  #colourCount = length(unique(rld$samples))
  #getPalette = colorRampPalette(brewer.pal(9, "Blues"))
  #fill=getPalette(colourCount)
  #tol21rainbow= c("#771155", "#AA4488", "#CC99BB", "#114477", "#4477AA", 
  #                "#77AADD", "#117777", "#44AAAA", "#77CCCC", "#117744",
  #                "#44AA77", "#88CCAA", "#777711", "#AAAA44", "#DDDD77",
  #                "#774411", "#AA7744", "#DDAA77", "#771122", "#AA4455", "#DD7788")
  #distplot_file_name <- paste(outputname,"/",outputname,"distPlot.pdf", sep="")
  #cairo_pdf(filename = distplot_file_name,
  #          bg = "white")
  #pheatmap(samplePoisDistMatrix,
  #         clustering_distance_rows=poisd$dd,
  #         clustering_distance_cols=poisd$dd,
  #         col=tol21rainbow,main="distance matrix (poissonsDistance) plot")
  #dev.off()
  # write out the rlog transformed data for future use
  write.table(assay(rld),file=normfile,sep="\t")
  print(head(assay(rld), 3))
  ntop=1000
  Pvars <- rowVars(assay(rld))
  select <- order(Pvars, decreasing = TRUE)[seq_len(min(ntop, length(Pvars)))]
  PCA <- prcomp(t(assay(rld)[select, ]), scale = T)
  head(PCA)
  #Scree plot
  scree_plot_file_name <- paste(outputname,"/",outputname,"_Scree.pdf", sep="")
  cairo_pdf(filename = scree_plot_file_name,
            bg = "white")
  plot(PCA, type="l", main="Scree plot")
  dev.off()
  percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2),1)
  print(colData(rld)$condition)
  pcadata = data.frame(PC1 = PCA$x[,1],
                       PC2 = PCA$x[,2],
                       PC3 = PCA$x[,3],
                       PC4 = PCA$x[,4],
                       condition = colData(rld)$condition) # sampleNumber = colData(rld)$sampleNumber , or , colortemp = y$colors,# may try
  print(pcadata)
  #print(pcadata$colortemp)
 # cols <- c("Metformin:PM" = "blue","Vehicle:PBS" = "darkgreen", "Vehicle:PM" = "orange","Metformin:PBS" = "red")
 #(qplot(PC1, PC2, data = pcadata, color = condition))
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC1vPC2_plot.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name,
            bg = "white")
  p1<-ggplot(pcadata, aes(PC1, PC2, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  #p + geom_text(size=2)
  p1<-p1+ scale_color_manual(values=cols)
  print(p1) # can be renamed to pc1_2
  dev.off()
  #labeled
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC1vPC2_plot_labeled.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name,
            bg = "white")
  p1<-ggplot(pcadata, aes(PC1, PC2, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p1<-p1+ scale_color_manual(values=cols)
  p1<-p1 + geom_label(size=3)
  print(p1) # can be renamed to pc1_2
  dev.off()
  #second Vs 3rd
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC2vPC3_plot.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name , bg = "white")
  p2<-ggplot(pcadata, aes(PC2, PC3, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC2: ",percentVar[2],"% variance")) +
    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  #p + geom_text(size=2)
  p2<-p2+ scale_color_manual(values=cols)
  print(p2) # pc2_3
  dev.off()
  #labeled
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC2vPC3_plot_labeled.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name , bg = "white")
  p2<-ggplot(pcadata, aes(PC2, PC3, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC2: ",percentVar[2],"% variance")) +
    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p2<-p2+ scale_color_manual(values=cols)
  p2<-p2+geom_label(size=3)
  print(p2) # pc2_3
  dev.off()
  #3rd vs fourth
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC3vPC4_plot.pdf", sep="")
  cairo_pdf(filename =pca_plot_file_name, bg = "white")
  p3<-ggplot(pcadata, aes(PC3, PC4, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC3: ",percentVar[3],"% variance")) +
    ylab(paste0("PC4: ",percentVar[4],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  #p + geom_text(size=2)
  p3<-p3+ scale_color_manual(values=cols)
  print(p3) # pc3_4
  dev.off()
  #labeled
  pca_plot_file_name <- paste(outputname,"/",outputname,"_PC3vPC4_plot_labeled.pdf", sep="")
  cairo_pdf(filename =pca_plot_file_name, bg = "white")
  p3<-ggplot(pcadata, aes(PC3, PC4, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC3: ",percentVar[3],"% variance")) +
    ylab(paste0("PC4: ",percentVar[4],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  #p + geom_text(size=2)
  p3<-p3+ scale_color_manual(values=cols)
  p3<-p3+geom_label(size=3)
  print(p3) # pc3_4
  dev.off()
  #
 # p1+guides(col=guide_legend(nrow = 8))
 # p1
}



DE_summary<-function(x){
  if (!file.exists(x)) {
  stop(paste("Input file doesn't exist:", x))
  } else {
  message(paste("Input file found:", x))
  }
  y<-read.delim(x,header = T)
  z<-filter(y, up == 1 | dn == 1)
  print(paste0("for comparison :", x))
  print(paste0("Total DE genes : ", dim(z)[1]))
  upgenes<-filter(y,up == 1)
  print(paste0("upregualted :",dim(upgenes)[1]))
  downgenes<-filter(y,dn == 1)
  print(paste0("Downregulated :",dim(downgenes)[1]))
  #y %>% 
  #  summarise(foldchange = mean(logFC), 
  #            min_fc = min(logFC),
  #            max_fc = max(logFC),
  #            total = n())
  min1<-min(y$logFC)
  max1<-max(y$logFC)
  print(paste0("Range of logFC: ", round(min1,2), " to ",round(max1,2)))
}

#volcano plots -> needs an update
Volc_plot<-function(a){
  if (!file.exists(a)) {
  stop(paste("Input file doesn't exist:", a))
  } else {
  message(paste("Input file found:", a))
  }
	y<-read.delim(a,header = T)
	rownames(y)<-make.names(y$gene, unique=TRUE)
	pdfname<-paste0("volc_",a,".pdf")
	pdf(filename = pdfname , bg = "white")
	with(y, plot(logFC, -log10(adj.p), pch=20, main=a, xlim=c(-10,10),ylim=c(0,150)))
    with(subset(y, (abs(logFC)>1)& adj.p< 0.05), points(logFC, -log10(adj.p), pch=20, col=ifelse((logFC < 0 & adj.p< 0.05),'blue','red')))
    abline(h=1.3,col="black")
    dev.off()
}
# labelled volcano plots
Volc_plot_labeled<-function(b){
  if (!file.exists(b)) {
  stop(paste("Input file doesn't exist:", b))
  } else {
  message(paste("Input file found:", b))
  }
  y<-read.delim(b,header = T)
  rownames(y)<-make.names(y$gene, unique=TRUE)
  pdfname<-paste0("Labeled_Volc",b,".pdf")
  pdf(file = pdfname , bg = "white")
  with(y, plot(logFC, -log10(adj.p), pch=20, main=b, xlim=c(-10,10),ylim=c(0,150)))
  with(subset(y, (abs(logFC)>1)& adj.p< 0.05), points(logFC, -log10(adj.p), pch=20, col=ifelse((logFC < 0 & adj.p< 0.05),'blue','red')))
  with(subset(file, adj.p<.05 & abs(logFC)>1), textxy(logFC, -log10(adj.p), labs=gene, cex=.6))
  abline(h=1.3,col="black")
  dev.off()
}
# annotate the raw counts data # mice only
annotate_files<-function(c){
  if (!file.exists(c)) {
  stop(paste("Input file doesn't exist:", c))
  } else {
  message(paste("Input file found:", c))
  }
  data1<-read.delim(c,header = T)
  #if (!('ENS' %like% row.names(data1))) {print("rownames of file must be ensembl ID's")}
  mart <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")
  anno_mart <- getBM(mart=mart, attributes=c('ensembl_gene_id','external_gene_name','description'))
  anno_match <- match(rownames(data1),anno_mart$ensembl_gene_id)
  data1$gene<-anno_mart[anno_match,'external_gene_name']
  filename1<-paste0("annotated_",c)
  data1<-data1[,c(ncol(data1),1:(ncol(data1)-1))]
  write.table(data1, file = filename1, row.names = TRUE,sep = "\t")
}




